name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 2 UTC every day
    - cron: "@hourly"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
